export const UPDATE_LOG_TEXT = "UPDATE_LOG_TEXT";
export const UPDATE_LOADING_STATUS = "UPDATE_LOADING_STATUS";
export const UPDATE_XHR_STATUS = "UPDATE_XHR_STATUS";
export const RETRIEVE_LOGS_SUCCESSFULLY = "RETRIEVE_LOGS_SUCCESSFULLY";
